% BIOASTER
%> @file		BaseLearnerConfig.m
%> @class		biotracs.atlas.model.BaseLearnerConfig
%> @link		http://www.bioaster.org
%> @copyright	Copyright (c) 2014, Bioaster Technology Research Institute (http://www.bioaster.org)
%> @license		BIOASTER
%> @date		6 mar. 2015

classdef (Abstract) BaseLearnerConfig < biotracs.core.mvc.model.ProcessConfig
    
    properties(Constant)
    end
    
    properties(SetAccess = protected)
    end

    % -------------------------------------------------------
    % Public methods
    % -------------------------------------------------------
    
    methods
        
        % Constructor
        function this = BaseLearnerConfig()
            this@biotracs.core.mvc.model.ProcessConfig();
            this.createParam(...
                'Center', true, ...
                'Constraint', biotracs.core.constraint.IsBoolean() ...
            );
            this.createParam(...
                'Scale', 'uv', ...
                'Constraint', biotracs.core.constraint.IsInSet({'uv','pareto','none'}) ...
            );
            this.createParam(...
                'StandardizationDirection', 'column', ...
                'Constraint', biotracs.core.constraint.IsInSet({'column','row'}) ...
            );
        
            this.createParam(...
                'StandardizeOutputs', true, ...
                'Constraint', biotracs.core.constraint.IsBoolean() ...
            );
        
            this.createParam(...
                'LogTransform', false, ...
                'Constraint', biotracs.core.constraint.IsBoolean() ...
            );
            this.createParam(...
                'kFoldCrossValidation', 0, ...
                'Constraint', biotracs.core.constraint.IsGreaterThan(0) ...
            );
            this.createParam(...
                'MonteCarloRepetition', 1, ...
                'Constraint', biotracs.core.constraint.IsGreaterThan(1) ...
            );
            this.createParam(...
                'MonteCarloPermutation', 0, ...
                'Constraint', biotracs.core.constraint.IsGreaterThan(0) ...
            );
        end
        
        
    end
    
    % -------------------------------------------------------
    % Protected methods
    % -------------------------------------------------------
    
    methods(Access = protected)
    end

end
