classdef GenericMLWorkflowTests < matlab.unittest.TestCase
    
    properties (TestParameter)
    end
    
    properties
        workingDir = fullfile(biotracs.core.env.Env.workingDir(), '/biotracs/atlas/GenericMLWorkflowTests');
    end

    methods (Test)

        function testAutoMLWorkflowWithClassification(testCase)
            s1 = RandStream.create('mrg32k3a','Seed', 0);
            s0 = RandStream.setGlobalStream(s1);
            
            trainingFilePath = '../testdata/generic_ml_workflow/data_xy1.csv';
            testFilePath = '../testdata/generic_ml_workflow/data_test.csv';
            w = biotracs.atlas.model.GenericMLWorkflow();
            w.getConfig()...
                .updateParamValue('WorkingDirectory', testCase.workingDir);

            trDataFileImporter = w.getNode('TrainingDataImporter');
            trDataFileImporter.addInputFilePath(trainingFilePath);        

            teDataFileImporter = w.getNode('TestDataImporter');
            teDataFileImporter.addInputFilePath(testFilePath);
            
            w.writeParamValues(...
                'PcaLearner:NbComponents', 10, ...
                'PcaLearnerViewExporter:ViewNames', {'ScorePlot','ScorePlot'}, ...
                'PcaLearnerViewExporter:ViewLabels', {'2DPlot','3DPlot'}, ...
                'PcaLearnerViewExporter:ViewParameters', {...
                    {'NbComponents', 2, 'GroupList', {'Group'}, 'LabelFormat', {'Group:([^_]*)'}},...
                    {'NbComponents', 3, 'GroupList', {'Group'}, 'LabelFormat', {'Group:([^_]*)'}}...
                }, ...
                ...
                'PlsLearner:NbComponents', 20, ...
                'PlsLearner:kFoldCrossValidation', Inf, ...
                'PlsLearnerViewExporter:ViewNames', {'ScorePlot'}, ...
                'PlsLearnerViewExporter:ViewParameters', {...
                    {'NbComponents', 2, 'GroupList', {'Group'}, 'LabelFormat', {'Group:([^_]*)'}}...
                }, ...
                ...
                'ModelSelector:NbComponents', 10, ...
                'ModelSelector:MaxNbVariablesToSelect', 10, ...
                'ModelSelector:kFoldCrossValidation', 10, ...
                'ModelSelector:MonteCarloPermutation', 500, ...
                'ModelSelector:PValue', 0.1, ...
                'ModelSelectorViewExporter:ViewNames', {'SelectedModelMap','PerformancePlot'}, ...
                'ModelSelectorViewExporter:ViewParameters', {}, ...
                ...
                'ReducedPlsLearner:NbComponents', 20, ...
                'ReducedPlsLearner:kFoldCrossValidation', Inf, ...
                'ReducedPlsLearnerViewExporter:ViewNames', {'ScorePlot'}, ...
                'ReducedPlsLearnerViewExporter:ViewParameters', {...
                    {'NbComponents', 2, 'GroupList', {'Group'}, 'LabelFormat', {'Group:([^_]*)'}}...
                 }, ...
                'ReducedPlsPredictor:ReplicatePatterns', {'Group'}, ... 
                'ReducedPlsPredictorViewExporter:ViewNames', {'YPredictionPlot', 'YPredictionScoreHeatMap', 'YPredictionScoreHeatMap'}, ...
                'ReducedPlsPredictorViewExporter:ViewLabels', {'YPredictionPlot', 'YPredictionScoreHeatMap', 'YPredictionScoreAverageHeatMap'}, ...
                'ReducedPlsPredictorViewExporter:ViewParameters', {...
                    {'GroupList', {'Group'}, 'LabelFormat', {'Group:([^_]*)'}}, ...
                    {'LabelFormat', {'Group:([^_]*)'}}, ...
                    {'LabelFormat', {'Group:([^_]*)'}, 'ShowAverage', true} ...
                }, ...
                ...
                'ReducedPlsLearnerResultExporter:NameFilter', 'CrossValidationVariableRanking|(^RegCoef$)|VarExplained|Scores|ClassSeparator|Stats', ...
                ...
                'BlindPlsPredictorViewExporter:ViewNames', {'YPredictionPlot'}, ...
                'BlindPlsPredictorViewExporter:ViewParameters', {...
                    {'GroupList', {'Group'}, 'LabelFormat', {'Group:([^_]*)'}}...
                }, ...
                ...
                'DiffProcess:GroupPatterns', {'Group'}, ...
                'DiffProcess:PValueThreshold', 0.05, ...
                'DiffProcess:FoldChangeThreshold', 1, ...
                'DiffProcessViewExporter:ViewNames', {'VolcanoPlot', 'VolcanoPlot'}, ...
                'DiffProcessViewExporter:ViewLabels', {'fc=1', 'fc=1.5'}, ...
                'DiffProcessViewExporter:ViewParameters', {...
                    {'PValueThreshold', 0.05, 'FoldChangeThreshold', 1, 'LabelFormat', 'none'},...
                    {'PValueThreshold', 0.05, 'FoldChangeThreshold', 1.5, 'LabelFormat', 'none'}...
                }, ...
                ...
                'PartialDiffProcess:NbComponents', 2, ...
                'PartialDiffProcess:PValue', 0.05, ...
                'PartialDiffProcess:GroupPatterns', {'Group'}, ...
                ...
                'BlindPlsPredictor:ReplicatePatterns', {'Group'}, ... 
                'BlindPlsPredictorViewExporter:ViewNames', {'YPredictionPlot', 'YPredictionScoreHeatMap', 'YPredictionScoreHeatMap'}, ...
                'BlindPlsPredictorViewExporter:ViewLabels', {'YPredictionPlot', 'YPredictionScoreHeatMap', 'YPredictionScoreAverageHeatMap'}, ...
                'BlindPlsPredictorViewExporter:ViewParameters', {...
                    {'GroupList', {'Group'}, 'LabelFormat', {'Group:([^_]*)'}}, ...
                    {'LabelFormat', {'Group:([^_]*)'}}, ...
                    {'LabelFormat', {'Group:([^_]*)'}, 'ShowAverage', true} ...
                 } ...
                );
            w.run();
            
            RandStream.setGlobalStream(s0);
        end

    end

end